name: Build Cardano Addresses

on:
  push:
    tags:
      - 'cardano-addresses-v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Cardano Addresses tag/branch to build (e.g., v3.15.0)'
        required: true
        default: 'master'
      ghc_version:
        description: 'GHC version to use'
        required: false
        default: '9.10.1'
      cabal_version:
        description: 'Cabal version to use'
        required: false
        default: '3.12.1.0'

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine cardano-addresses tag
        id: determine_tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # Extract version from binary-specific tag (e.g., cardano-addresses-v3.15.0 -> v3.15.0)
            TAG_NAME="${{ github.ref_name }}"
            if [[ "$TAG_NAME" == cardano-addresses-* ]]; then
              CARDANO_TAG="${TAG_NAME#cardano-addresses-}"
            else
              echo "Error: Tag must start with 'cardano-addresses-'"
              exit 1
            fi
          else
            CARDANO_TAG="${{ github.event.inputs.tag }}"
          fi
          echo "cardano_tag=$CARDANO_TAG" >> $GITHUB_OUTPUT
          echo "Building cardano-addresses from tag/branch: $CARDANO_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build cardano-addresses for Linux ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg CARDANO_ADDRESSES_TAG=${{ steps.determine_tag.outputs.cardano_tag }} \
            --build-arg GHC_VERSION=${{ github.event.inputs.ghc_version || '9.10.1' }} \
            --build-arg CABAL_VERSION=${{ github.event.inputs.cabal_version || '3.12.1.0' }} \
            -f Dockerfile.cardano-addresses-linux-arm64 \
            -t cardano-addresses-builder \
            --load .

      - name: Extract binary from container
        run: |
          mkdir -p artifacts
          docker run --rm -v $(pwd)/artifacts:/output cardano-addresses-builder sh -c "cp /usr/local/bin/cardano-addresses /output/"
          
      - name: Verify binary
        run: |
          file artifacts/cardano-addresses
          ls -la artifacts/

      - name: Compress binary
        run: |
          cd artifacts
          tar -czf cardano-addresses-linux-arm64.tar.gz cardano-addresses
          sha256sum cardano-addresses-linux-arm64.tar.gz > cardano-addresses-linux-arm64.tar.gz.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cardano-addresses-linux-arm64
          path: |
            artifacts/cardano-addresses-linux-arm64.tar.gz
            artifacts/cardano-addresses-linux-arm64.tar.gz.sha256

  release:
    needs: build-linux-arm64
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Determine release tag
        id: release_tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG_NAME="${{ github.ref_name }}"
            if [[ "$TAG_NAME" == cardano-addresses-* ]]; then
              CARDANO_TAG="${TAG_NAME#cardano-addresses-}"
            else
              CARDANO_TAG="$TAG_NAME"
            fi
          else
            CARDANO_TAG="${{ github.event.inputs.tag }}"
          fi
          echo "cardano_tag=$CARDANO_TAG" >> $GITHUB_OUTPUT
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Cardano Addresses ${{ steps.release_tag.outputs.cardano_tag }}
          body: |
            ## Cardano Addresses Binary Release
            
            This release contains the `cardano-addresses` binary compiled for various platforms.
            Built from IntersectMBO/cardano-addresses tag: `${{ steps.release_tag.outputs.cardano_tag }}`
            
            ### Linux ARM64 (Raspberry Pi)
            - `cardano-addresses-linux-arm64.tar.gz` - Binary for Linux ARM64
            - `cardano-addresses-linux-arm64.tar.gz.sha256` - SHA256 checksum
            
            ### Installation
            
            1. Download the appropriate binary for your platform
            2. Verify the checksum: `sha256sum -c cardano-addresses-linux-arm64.tar.gz.sha256`
            3. Extract: `tar -xzf cardano-addresses-linux-arm64.tar.gz`
            4. Make executable: `chmod +x cardano-addresses`
            5. Move to PATH: `sudo mv cardano-addresses /usr/local/bin/`
            
            ### Usage
            ```bash
            cardano-addresses --help
            ```
            
            ### Release Notes
            This binary was built using:
            - GHC 9.10.1
            - Cabal 3.12.1.0 
            - Static linking for maximum portability
          files: |
            artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}