name: Build Cardano Addresses

on:
  push:
    tags:
      - 'cardano-addresses-*'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile.cardano-addresses-*'
      - '.github/workflows/build-cardano-addresses.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Cardano Addresses tag/branch to build (e.g., 4.0.0)'
        required: true
        default: 'master'
      ghc_version:
        description: 'GHC version to use'
        required: false
        default: '9.10.1'
      cabal_version:
        description: 'Cabal version to use'
        required: false
        default: '3.12.1.0'

jobs:
  test-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build cardano-addresses for Linux x64 (no emulation)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg CARDANO_ADDRESSES_TAG=4.0.0 \
            --build-arg GHC_VERSION=9.10.1 \
            --build-arg CABAL_VERSION=3.12.1.0 \
            --cache-from=type=gha,scope=test-amd64 \
            --cache-to=type=gha,mode=max,scope=test-amd64 \
            -f Dockerfile.cardano-addresses-linux-arm64 \
            --progress=plain \
            -t cardano-addresses-test \
            --load .

      - name: Test binary functionality
        run: |
          echo "Testing cardano-addresses binary..."
          docker run --rm cardano-addresses-test cardano-addresses --version
          echo "Testing help command..."
          docker run --rm cardano-addresses-test cardano-addresses --help
          echo "Testing user permissions..."
          docker run --rm cardano-addresses-test whoami
          echo "✅ All tests passed!"

  build-linux-arm64:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine cardano-addresses tag
        id: determine_tag
        run: |
          set -euo pipefail
          
          if [ "${{ github.event_name }}" = "push" ]; then
            # Extract version from binary-specific tag (e.g., cardano-addresses-4.0.0 -> 4.0.0)
            TAG_NAME="${{ github.ref_name }}"
            if [[ "$TAG_NAME" == cardano-addresses-* ]]; then
              CARDANO_TAG="${TAG_NAME#cardano-addresses-}"
              if [ -z "$CARDANO_TAG" ]; then
                echo "Error: Invalid tag format - version part is empty"
                exit 1
              fi
            else
              echo "Error: Tag must start with 'cardano-addresses-', got: $TAG_NAME"
              exit 1
            fi
          else
            CARDANO_TAG="${{ github.event.inputs.tag }}"
            if [ -z "$CARDANO_TAG" ]; then
              echo "Error: Tag input cannot be empty"
              exit 1
            fi
          fi
          
          echo "cardano_tag=$CARDANO_TAG" >> $GITHUB_OUTPUT
          echo "✅ Building cardano-addresses from tag/branch: $CARDANO_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build cardano-addresses for Linux ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg CARDANO_ADDRESSES_TAG=${{ steps.determine_tag.outputs.cardano_tag }} \
            --build-arg GHC_VERSION=${{ github.event.inputs.ghc_version || '9.10.1' }} \
            --build-arg CABAL_VERSION=${{ github.event.inputs.cabal_version || '3.12.1.0' }} \
            --cache-from=type=gha,scope=build-arm64 \
            --cache-to=type=gha,mode=max,scope=build-arm64 \
            -f Dockerfile.cardano-addresses-linux-arm64 \
            -t cardano-addresses-builder \
            --load .

      - name: Extract binary from container
        run: |
          mkdir -p artifacts
          docker run --rm -v $(pwd)/artifacts:/output cardano-addresses-builder sh -c "cp /usr/local/bin/cardano-addresses /output/"
          
      - name: Verify binary
        run: |
          file artifacts/cardano-addresses
          ls -la artifacts/

      - name: Compress binary
        run: |
          cd artifacts
          tar -czf cardano-addresses-linux-arm64.tar.gz cardano-addresses
          sha256sum cardano-addresses-linux-arm64.tar.gz > cardano-addresses-linux-arm64.tar.gz.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cardano-addresses-linux-arm64
          path: |
            artifacts/cardano-addresses-linux-arm64.tar.gz
            artifacts/cardano-addresses-linux-arm64.tar.gz.sha256

  release:
    needs: build-linux-arm64
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Determine release tag
        id: release_tag
        run: |
          set -euo pipefail
          
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG_NAME="${{ github.ref_name }}"
            if [[ "$TAG_NAME" == cardano-addresses-* ]]; then
              CARDANO_TAG="${TAG_NAME#cardano-addresses-}"
            else
              CARDANO_TAG="$TAG_NAME"
            fi
          else
            CARDANO_TAG="${{ github.event.inputs.tag }}"
          fi
          
          echo "cardano_tag=$CARDANO_TAG" >> $GITHUB_OUTPUT
          echo "✅ Release tag determined: $CARDANO_TAG"
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Cardano Addresses ${{ steps.release_tag.outputs.cardano_tag }}
          body: |
            Compiled binary release for cardano-addresses v${{ steps.release_tag.outputs.cardano_tag }}.
            
            **Download:** `cardano-addresses-linux-arm64.tar.gz`  
            **Verify:** `sha256sum -c cardano-addresses-linux-arm64.tar.gz.sha256`  
            **Extract:** `tar -xzf cardano-addresses-linux-arm64.tar.gz`  
            **Run:** `./cardano-addresses --version`
          files: |
            artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}